### ISSUE TITLE
Can't run the basic usage

### ISSUE THREAD

**Issue by jmetchebarne** [BeelGroup/Auto-Surprise#35]
Hello, I was trying to use auto-surprise and run the Basic Usage, it does run properly the baseline loss part, but as soon as it start with the svd algorithm, I get the following error:

```
Starting process with svd algorithm
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\jmetchebarne\anaconda3\envs\Proyecto Recomendaciones\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\jmetchebarne\anaconda3\envs\Proyecto Recomendaciones\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
Traceback (most recent call last):
  File "C:\Users\jmetchebarne\anaconda3\envs\Proyecto Recomendaciones\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-56575903e07a>", line 19, in <module>
    max_evals=10
  File "C:\Users\jmetchebarne\anaconda3\envs\Proyecto Recomendaciones\lib\site-packages\auto_surprise\engine.py", line 96, in train
    best_algo, best_params, best_score, tasks = strategy.evaluate()
  File "C:\Users\jmetchebarne\anaconda3\envs\Proyecto Recomendaciones\lib\site-packages\auto_surprise\strategies\continuous_parallel.py", line 50, in evaluate
    p.start()
  File "C:\Users\jmetchebarne\anaconda3\envs\Proyecto Recomendaciones\lib\multiprocessing\process.py", line 115, in start
    self._popen = self._Popen(self)
  File "C:\Users\jmetchebarne\anaconda3\envs\Proyecto Recomendaciones\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\jmetchebarne\anaconda3\envs\Proyecto Recomendaciones\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\jmetchebarne\anaconda3\envs\Proyecto Recomendaciones\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\jmetchebarne\anaconda3\envs\Proyecto Recomendaciones\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle module objects
```

Not sure if I'm doing something wrong here, to be honest, I just executed the code posted:

```
from surprise import Dataset
from auto_surprise.engine import Engine

# Load the dataset
data = Dataset.load_builtin('ml-100k')

# Intitialize auto surprise engine
engine = Engine(verbose=True)

# Start the trainer
best_algo, best_params, best_score, tasks = engine.train(
    data=data, 
    target_metric='test_rmse', 
    cpu_time_limit=60 * 60, 
    max_evals=100
)
```

Any help is really appreciated.

**Comment by thededlier** [comment]
HI @jmetchebarne. Unfortunately, the current implementation of Auto-Surprise does not support running it on Windows. One workaround on Windows is to use [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10). Hope this helps

**Comment by jmetchebarne** [comment]
> HI @jmetchebarne. Unfortunately, the current implementation of Auto-Surprise does not support running it on Windows. One workaround on Windows is to use [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10). Hope this helps

I see, makes sense. I'll try using WSL and try it out. Thanks for the answer!

**Comment by alitrack** [comment]
I got the  same issue on macOS 

Python 3.8
auto_surprise 0.1.7
Available CPUs: 8
